version:           "2"
services:
  web:
    build:         .
    ports:
      - "0.0.0.0:80:80"
    networks:
      - nodeapp-network
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image:         mongo
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver:        bridge
